print("Daniel olivares")
print("Abdias estuvo aqui")
print("============================")
print(" NUESTRO PRIMER PROGRAMA PYTHON")
print("============================")
print("Nombres: Daniel, Abdul, Angel, Jhonathan")
print("Carrera: Ingeniería de Sistemas e Innovacion Digital")
print("Primer Semestre")
print("Estoy aprendiendo Git y GitHub")